### ISSUE TITLE
MacOS X default shell

### ISSUE THREAD

**Issue by ebukan21** [zanydazanydnaya/21school_stuff#1]
Стандартной оболочкой в MacOS X давно является zsh, а не bash.
Наверное, есть смысл либо добавить в текст рецепт по настройке bash в качестве оболочки по умолчанию, либо расписать все связанные с этим ключевые моменты. И в первую очередь - про стартовые скрипты, а то многие по советам из интернетов и от линкусоидов пишут что-нибудь в ~/.bashrc, а оно не работает, надо было писать в ~/.zshrc

**Comment by zanydazanydnaya** [comment]
> Стандартной оболочкой в MacOS X давно является zsh, а не bash.
Спорно, что давно. Они переехали на zsh только с Catalina, а она с 2019 года + у меня отсутствовал zsh на маке в школе. Но не суть, я по большей части описывал инструкцию для subsystem linux для win10 и под zsh, и собственно основной файл под конфиги оболочки я прописывал в ~/.zshrc, а не под ~/.bashrc.

> Наверное, есть смысл либо добавить в текст рецепт по настройке bash в качестве оболочки по умолчанию, либо расписать все связанные с этим ключевые моменты.
Если есть желание дополнить статью, то я только за.
